name: KiteNative
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: cn.kitlib.kitemac
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO
targets:
  KiteNative:
    type: application
    platform: macOS
    sources:
      - path: KiteNative
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: KiteNative/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: cn.kitlib.kitemac
        PRODUCT_NAME: KiteNative
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets:
        - KiteNativeUITests
    dependencies:
      - target: KiteWidgetExtension
  KiteNativeUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: KiteNativeUITests
    dependencies:
      - target: KiteNative
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cn.kitlib.kitemac.uitests
        PRODUCT_NAME: KiteNativeUITests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: KiteNative
  KiteWidgetExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: KiteWidgetExtension
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: KiteWidgetExtension/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: cn.kitlib.kitemac.widget
        PRODUCT_NAME: KiteWidgetExtension
        GENERATE_INFOPLIST_FILE: NO
        SKIP_INSTALL: YES
        APPLICATION_EXTENSION_API_ONLY: YES
